spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/$dbname
    username: $username
    password: $password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
        show_sql: false
        hibernate.hbm2ddl.auto: none

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml
