spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asseco
    username: postgres
    password: dontgotosql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 2000
        generate_statistics: false
        show_sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml
